ALTER TABLE inquiries ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at AT TIME ZONE 'UTC';
ALTER TABLE inquiries ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

-- 修改updated_at字段类型为TIMESTAMPTZ
ALTER TABLE inquiries ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at AT TIME ZONE 'UTC';
ALTER TABLE inquiries ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE inquiry_items ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at AT TIME ZONE 'UTC';
ALTER TABLE inquiry_items ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

-- 修改updated_at字段类型为TIMESTAMPTZ
ALTER TABLE inquiry_items ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at AT TIME ZONE 'UTC';
ALTER TABLE inquiry_items ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;


ALTER TABLE countries ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at AT TIME ZONE 'UTC';
ALTER TABLE countries ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

-- 修改updated_at字段类型为TIMESTAMPTZ
ALTER TABLE countries ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at AT TIME ZONE 'UTC';
ALTER TABLE countries ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE states ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at AT TIME ZONE 'UTC';
ALTER TABLE states ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

-- 修改updated_at字段类型为TIMESTAMPTZ
ALTER TABLE states ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at AT TIME ZONE 'UTC';
ALTER TABLE states ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;

-- 修改updated_at字段类型为TIMESTAMPTZ
ALTER TABLE tags ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at AT TIME ZONE 'UTC';
ALTER TABLE tags ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;

-- 修改updated_at字段类型为TIMESTAMPTZ
ALTER TABLE tags ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at AT TIME ZONE 'UTC';
ALTER TABLE tags ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;
